<a href="https://colab.research.google.com/github/nav-lak/python_library/blob/main/svm_classification_iris_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

# SVM Classification using Scikit-Learn
# -----------------------------
# Step 1 : Import Libraries
# -----------------------------

import pandas as pd

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix
)

# -----------------------------
# Step 2 : Load Iris Dataset
# -----------------------------

iris = datasets.load_iris()

# -----------------------------
# Step 3 : Create DataFrame
# -----------------------------

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# -----------------------------
# Step 4 : Add Target Column
# -----------------------------

df["target"] = iris.target

# -----------------------------
# Step 5 : Add Flower Names
# -----------------------------

df["flower_name"] = df["target"].map({
    0: "setosa",
    1: "versicolor",
    2: "virginica"
})

df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,flower_name
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,virginica
146,6.3,2.5,5.0,1.9,2,virginica
147,6.5,3.0,5.2,2.0,2,virginica
148,6.2,3.4,5.4,2.3,2,virginica
149,5.9,3.0,5.1,1.8,2,virginica

In [5]:
print("=" * 60)
print("=" *20,"Complete Dataset","="*20)
print("=" * 60)
df.head()

============================================================
==================== Complete Dataset ====================
============================================================

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,flower_name
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa

In [8]:
# Step 7 : Separate Features
# -----------------------------

X = df.drop(
    columns=["target", "flower_name"]
)
X

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [11]:
# Step 8 : Target Variable
y = df["target"]
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [14]:
# Step 9 : Check Shapes
# -----------------------------

print("\nShape of X :", X.shape)
print("Shape of y :", y.shape)

Shape of X : (150, 4)
Shape of y : (150,)

In [15]:

# Step 10 : Train-Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    shuffle=True,
    stratify=y
)

print("\nTraining Shape :", X_train.shape)
print("Testing Shape  :", X_test.shape)

Training Shape : (120, 4)
Testing Shape  : (30, 4)

In [16]:
# Step 11 : Create SVM Model
model = SVC()
# -----------------------------
# Step 12 : Display Parameters
# -----------------------------
print("\nDefault Parameters\n")

print(model.get_params())

Default Parameters

{'C': 1.0, 'break_ties': False, 'cache_size': 200, 'class_weight': None, 'coef0': 0.0, 'decision_function_shape': 'ovr', 'degree': 3, 'gamma': 'scale', 'kernel': 'rbf', 'max_iter': -1, 'probability': False, 'random_state': None, 'shrinking': True, 'tol': 0.001, 'verbose': False}

In [17]:
# Step 13 : Train Model
# -----------------------------
model.fit(
    X_train,
    y_train
)

print("\nModel Trained Successfully")

Model Trained Successfully

In [18]:
# Step 14 : Prediction
y_pred = model.predict(
    X_test
)

In [21]:
# Step 15 : Predict Training Data
# -----------------------------

train_prediction = model.predict(
    X_train
)
# Step 16 : Accuracy
# -----------------------------

train_accuracy = accuracy_score(
    y_train,
    train_prediction
)
test_accuracy = accuracy_score(
    y_test,
    y_pred
)

print("\nTraining Accuracy")

print(f"{train_accuracy*100:.2f}%")

print("\nTesting Accuracy")

print(f"{test_accuracy*100:.2f}%")

Training Accuracy
98.33%

Testing Accuracy
96.67%

In [23]:
# -----------------------------
# Step 17 : Result DataFrame
# -----------------------------

result = pd.DataFrame({

    "Actual": y_test.reset_index(drop=True),

    "Predicted": y_pred

})

# -----------------------------
# Step 18 : Convert Numbers
# -----------------------------

result["Actual Flower"] = result["Actual"].map({

    0: "setosa",

    1: "versicolor",

    2: "virginica"

})

result["Predicted Flower"] = result["Predicted"].map({

    0: "setosa",

    1: "versicolor",

    2: "virginica"

})

# -----------------------------
# Step 19 : Correct Prediction
# -----------------------------

result["Correct?"] = (

    result["Actual"] == result["Predicted"]

)

print("\nPrediction Result")

print(result)

Prediction Result
    Actual  Predicted Actual Flower Predicted Flower  Correct?
0        0          0        setosa           setosa      True
1        2          2     virginica        virginica      True
2        1          1    versicolor       versicolor      True
3        1          1    versicolor       versicolor      True
4        0          0        setosa           setosa      True
5        1          1    versicolor       versicolor      True
6        0          0        setosa           setosa      True
7        0          0        setosa           setosa      True
8        2          2     virginica        virginica      True
9        1          1    versicolor       versicolor      True
10       2          2     virginica        virginica      True
11       2          2     virginica        virginica      True
12       2          2     virginica        virginica      True
13       1          1    versicolor       versicolor      True
14       0          0        setosa           setosa      True
15       0          0        setosa           setosa      True
16       0          0        setosa           setosa      True
17       1          1    versicolor       versicolor      True
18       1          1    versicolor       versicolor      True
19       2          2     virginica        virginica      True
20       0          0        setosa           setosa      True
21       2          2     virginica        virginica      True
22       1          1    versicolor       versicolor      True
23       2          2     virginica        virginica      True
24       2          2     virginica        virginica      True
25       1          2    versicolor        virginica     False
26       1          1    versicolor       versicolor      True
27       0          0        setosa           setosa      True
28       2          2     virginica        virginica      True
29       0          0        setosa           setosa      True

In [25]:
# Step 20 : Predict One Flower
# -----------------------------

new_flower = pd.DataFrame(

    [[5.1, 3.5, 1.4, 0.2]],

    columns=X.columns

)
prediction = model.predict(

    new_flower

)

print("\nPrediction for New Flower")

print(prediction)

print(

    "Flower Name :",

    iris.target_names[prediction[0]]

)

Prediction for New Flower
[0]
Flower Name : setosa